FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el código del repo dentro de la imagen
COPY . .

# Cambiar a la carpeta del servicio ETL
WORKDIR /app/cloud_run/etl_cesens

CMD ["functions-framework", "--target=backfill_cesens", "--port=8080"]
