FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos TODO el repo
COPY . .

# AÑADIR ESTO: que /app esté en PYTHONPATH
ENV PYTHONPATH="/app:${PYTHONPATH}"

# Nos movemos a la carpeta del agente de riego
WORKDIR /app/cloud_run/irrigation_agent

CMD ["functions-framework", "--target=run_irrigation_agent", "--port=8080"]
